NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

ACCOUNTS=[
"GAIMV36WSTXZTW22DAGKMO34N4CWTOC4CZCKEAUIEHT47DQ2VS5FHJLY",
"GCL2EXSTHUTSDP75K6X6QIPHXNZ2Y55KC2H3BULW3FT53JGDVHYC4HFU",
"GB5NVPPV35WC2HXYTS73UGCQGYKJ5SZRD7P267LTRJRKGD53NDKKAXQ3"
]
VERSION="2.0.0"

[DOCUMENTATION]
ORG_NAME="ChemiTokens"
ORG_URL="https://www.chemitokens.org"
ORG_DESCRIPTION="The chemicoin is the future project that will grow exponentially and you need a single team that works together with one brief, one objective, one goal.Chemicoin will empower the crypto community with the ability to stabilize their portfolios by investing in real commodities."
ORG_TWITTER="@ChemiTokens"
ORG_LOGO="https://i.ibb.co/G3YMZjm/chemitokens-logo.png"
ORG_OFFICIAL_EMAIL="chemitokens@gmail.com"


[[CURRENCIES]]
code="xcb"
issuer="GAIMV36WSTXZTW22DAGKMO34N4CWTOC4CZCKEAUIEHT47DQ2VS5FHJLY"
anchor_asset="false"
name="Cobalt"
desc="Cobalt is an essential mineral used for batteries in electric cars, computers, and cell phones. Demand for cobalt is increasing as more electric cars are sold, particularly in Europe, where governments are encouraging the sales with generous environmental bonuses."
image="https://i.ibb.co/LvRv9fM/cobalt.png"
fixed_number=10000000
max_number=10000000
is_unlimited=false
#Cobalt was issued using the open and inclusive Stellar blockchain network.


[[CURRENCIES]]
code="xcp"
issuer="GCL2EXSTHUTSDP75K6X6QIPHXNZ2Y55KC2H3BULW3FT53JGDVHYC4HFU"
anchor_asset="false"
name="Copper"
desc="The copper industry is a major contributor to the global economy. Copper is more than just a mined metal; it provides jobs and promotes of a higher standard of living. The copper industry provides benefits to more than just the companies mining copper and fabricating products from it."
image="https://i.ibb.co/0Z46DN9/copper.png"
fixed_number=10000000
max_number=10000000
is_unlimited=false
#Copper was issued using the open and inclusive Stellar blockchain network.


[[CURRENCIES]]
code="xhg"
issuer="GB5NVPPV35WC2HXYTS73UGCQGYKJ5SZRD7P267LTRJRKGD53NDKKAXQ3"
anchor_asset="false"
name="Mercury"
desc="Mercury can be used to make thermometers, barometers and other scientific instruments. Mercury conducts electricity and is used to make silent, position dependent switches."
image="https://i.ibb.co/BskWxgt/mercury.png"
fixed_number=100000
max_number=100000
is_unlimited=false
#Mercury was issued using the open and inclusive Stellar blockchain network.




